### ISSUE TITLE
Functions without parameters

### ISSUE THREAD

**Issue by rmolinamir** [Stevenic/alphawave#11]
Hi @Stevenic 👋 

Piggybacking from #10, I ran into a few issues while working with the function calling API, it happened when declaring functions without parameters.

I was getting a 400 error when using functions with no `parameters`, I think this was originating client-side though.

I later found that if I declared `parameters` as an empty object it would basically enter a feedback loop inside the JSON response validator of the function, such as:

```sh
Hello, how can I help you?
User: show all items
REPAIRING RESPONSE:
null
feedback: "No arguments were sent with function call. Call the "getAll" with required arguments as a valid JSON object."
feedback: "No arguments were sent with function call. Call the "getAll" with required arguments as a valid JSON object."
feedback: "No arguments were sent with function call. Call the "getAll" with required arguments as a valid JSON object."
Response Repair Failed
```

Let me know if you'd like me to open a PR with a fix for this issue 😃

**Comment by Stevenic** [comment]
A PR would be great. I can publish a 0.6.2 update. I honestly hadn’t tested that so great catch

**Comment by rmolinamir** [comment]
Sounds good! I'll work on it later today or tomorrow, will open a PR once I get it working.

**Comment by Stevenic** [comment]
Can't wait!

**Comment by Stevenic** [comment]
Fixed by PR
