### ISSUE TITLE
Function calling API

### ISSUE THREAD

**Issue by voodoohop** [Stevenic/alphawave#5]
Love your approach. Any plans on making it work with the new Function Calling API?

**Comment by Stevenic** [comment]
@voodoohop I'm working on adding function support right now. I'm about 80% finished and hope to wrap up the work this week... 

https://github.com/Stevenic/alphawave/tree/stevenic/functions

This work will add much needed validation to the function calls predicted by the model. It will be impossible for the model to hallucinate non-existent functions or drop required parameters like it can today.

**Comment by Stevenic** [comment]
I also just added a discussions section

**Comment by Stevenic** [comment]
Completed
